### ISSUE TITLE
"TypeError: Cannot read property 'createdAt' of undefined"

### ISSUE THREAD

**Issue by dartmouthy** [tiffany352/twitter-archive-browser#28]
Firstly, thank you so much for this project! It will be so exciting if I can get it working.

With Alpha 4 I am still getting a range error with my zip (Loading archive failed
RangeError: File size (8990236118) is greater than possible Buffer: 2147483647 bytes)

But when I load the folder that was unzipped manually I still get this other error (Loading archive failed TypeError: Cannot read property 'createdAt' of undefined)

I checked account.js, and sure enough, there is a "createdAt" definition ("2015-09-11T20:18:09.776Z"), I'm not sure if this is what is creating the hangup?

Thank you for any direction you can provide, or if there is any info or help I can provide you to help solve this, please let me know!

**Comment by LonnyFoos** [comment]
I'm having the same problem.

**Comment by tiffany352** [comment]
Twitter changed their archive format about 2 weeks ago to no longer store the media inside of a compressed zip. As long as you unzip the archive first, the Alpha 6 version of the app I just released should be able to load your archive now. Let me know if that's not the case!
