### ISSUE TITLE
Loading archive failed

### ISSUE THREAD

**Issue by mmogithub** [tiffany352/twitter-archive-browser#29]
With "Twitter-Archive-Browser-Setup-0.1.0-alpha4" installed in W10.
After selecting a folder where full twitter data archive in uncompressed, the following error is shown:
"TypeError: s.tweet[Symbol.iterator] is not a function"

![Sin título](https://user-images.githubusercontent.com/11737147/72730911-c71c3500-3b92-11ea-8857-2909ac24f2c1.png)

**Comment by alkihis** [comment]
Recently, around mid-january, Twitter made changes to file tweet.js inside the archive. Tweets are now wrapped inside an object with a single "tweet" property.
Handling this case during parsing will fix the issue...
![image](https://user-images.githubusercontent.com/32335180/73023496-f39eae00-3e2b-11ea-8837-8d1e9257f3c0.png)

**Comment by tiffany352** [comment]
I just pushed an updated version of the app, let me know if that fixed it!

**Comment by mmogithub** [comment]
I'm speechless.
It works great. It's a beautiful application.
Thank you very much for the effort and for listening to us.
You are a great person and a great developer.
Thank you very much from the heart.

**Comment by mmogithub** [comment]
I forgot to mention that version tested that works like a charm is "Twitter-Archive-Browser-Setup-0.1.0-alpha6.exe"
An screenshot :)
Thanks again for great effort.
![Sin título](https://user-images.githubusercontent.com/11737147/73245362-5be2ec00-41ac-11ea-86c0-5b9b08af21ee.png)
